### ISSUE TITLE
Coded in python, Pls switch to another language

### ISSUE THREAD

**Issue by insyri** [Jeftaei/No-LT-ALLOWED#1]
Thx

**Comment by Jeftaei** [comment]
im gonna code ur mom in Python you dumb Fucking ts LOSER FUCK YOU!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by iminlikewithyou** [comment]
this issue is still affecting the codebase, probably should reopen
